a = int(input("Ingrese un numero entero "))
b = int(input("Ingrese un numero entero " ))
c = int(input("Ingrese un numero entero " ))

print("Usted ingresó los valores:", a, b, c )
print(a, "es mayor que", b, True )
print(a, "y", b, "son iguales", True )
print(a, "es el mayor de todos", True )
print(b, "es el menor de todos", True )
print(a, "es mayor que alguno de los otros dos", True )
print(a, "es menor o igual que alguno de los otros dos", True )
print("Los tres numeros son iguales", True )
print("Los tres numeros son distintos", True )
print(a, "es par", True )
print("alguno es par", True )
print("ninguno es par", True )
print("todos son pares", True )
print(a, "es multiplo de 3", True )
print(a, "es multiplo de 3 y de 5", True )
print(a, "es multiplo de 3 y par", True )
print(a, "-", b, "da un numero positivo", True )
print(a, "-", b, "da un numero par positivo", True )